version: "2.2"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5432:5432"
    volumes:
      - ./db_1:/var/lib/postgresql/data